on:
  webhook:
    method: get
    config:
      active: true
      force: true
jobs:
  test-curl-action:
    name: 'Perform REST API'
    runs-on: ubuntu-latest
    steps:
      - name: Get openweathermap
        uses: actionsflow/axios@v1
        id: weatherapi
        with:
          url: ${{ secrets.WETTER_URL }}
          method: 'GET'
      - name: Get current date
        id: date
        run: echo "::set-output name=wotag::$(date +'%A')"
      - name: Translate current date
        id: translate
        run: |
          if [ "${{steps.date.outputs.wotag}}" = "Monday" ]
          then
            echo "::set-output name=wotag::Montag"
          elif [ "${{steps.date.outputs.wotag}}" = "Tuesday" ]
          then
            echo "::set-output name=wotag::Dienstag"
          elif [ "${{steps.date.outputs.wotag}}" = "Wednesday" ]
          then
            echo "::set-output name=wotag::Mittwoch"
          elif [ "${{steps.date.outputs.wotag}}" = "Thursday" ]
          then
            echo "::set-output name=wotag::Donnerstag"
          elif [ "${{steps.date.outputs.wotag}}" = "Friday" ]
          then
            echo "::set-output name=wotag::'Freutag'"
          elif [ "${{steps.date.outputs.wotag}}" = "Saturday" ]
          then
            echo "::set-output name=wotag::Samstag"
          elif [ "${{steps.date.outputs.wotag}}" = "Sunday" ]
          then
            echo "::set-output name=wotag::Sonntag"
          else
            echo "::set-output name=wotag::Arbeitstag"
          fi
      - name: Sende an Webex
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBEX_URL_ROOMMRKS }}
          body: '{"markdown": "Dienstbeginn Markus<br>Ich wünsche Euch einen schönen ${{steps.translate.outputs.wotag}}!"}'
